{{/*
Inngest ALB Ingress
Kubernetes Ingress resource for external access to Inngest services using AWS ALB.
Only created when ingress.enabled is true.

This ingress provides:
- External HTTP/HTTPS access to the Inngest UI and API (port 8288)
- ALB actions for path forwarding
- TLS termination support
- Kubernetes 1.20+ networking.k8s.io/v1 API

Note: ALB does not natively rewrite paths like NGINX. Requests to /inngest/* are forwarded
to the service as-is. If Inngest expects root path "/", you may need a sidecar reverse proxy
or configure Inngest to serve under /inngest base path.
*/}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "inngest.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "inngest.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            service:
              name: {{ .serviceName | default "inngest-rewrite" }}
              port:
                name: {{ .servicePort | default "use-annotation" }}
          {{- end }}
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}
